package VIEW;

import DAO.EmprestimoDevolucaoDAO;
import DTO.EmprestimoDevolucaoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artur
 */
public class frmEmprestimoDevolucaoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmEmprestimoDevolucaoVIEW
     */
    public frmEmprestimoDevolucaoVIEW() {
        initComponents();
        listarValoresEmprestimoDevolucao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId_emprestimo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();
        txtId_livro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtData_emprestimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSituacao_emprestimo = new javax.swing.JTextField();
        btnEmprestimo = new javax.swing.JButton();
        btnDevolucao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimo = new javax.swing.JTable();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empréstimo / Devolução");

        jLabel1.setText("ID - Empréstimo");

        txtId_emprestimo.setEnabled(false);

        jLabel2.setText("ID - Cliente");

        jLabel3.setText("ID - Livro");

        jLabel4.setText("Data do Empréstimo");

        jLabel5.setText("Situação");

        txtSituacao_emprestimo.setEnabled(false);

        btnEmprestimo.setText("Empréstimo");
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        btnDevolucao.setText("Devolução");
        btnDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucaoActionPerformed(evt);
            }
        });

        tabelaEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID - Empréstimo", "ID - Cliente", "ID - Livro", "Data do Empréstimo", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tabelaEmprestimo);

        btnCarregarCampos.setText("Carregar Campos");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtId_livro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtId_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtId_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDevolucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtSituacao_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCarregarCampos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSituacao_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        if (txtId_cliente.getText().isEmpty() || txtId_livro.getText().isEmpty() || txtData_emprestimo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        } else {
            Emprestimo();
            listarValoresEmprestimoDevolucao();
            limparCampos();
        }


    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoActionPerformed
        if (txtId_emprestimo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione e carregue o empréstimo.");
        } else {
            Devolucao();
            listarValoresEmprestimoDevolucao();
            limparCampos();
        }
    }//GEN-LAST:event_btnDevolucaoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        limparCampos();
        Voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmprestimoDevolucaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmprestimoDevolucaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmprestimoDevolucaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmprestimoDevolucaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmprestimoDevolucaoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEmprestimo;
    private javax.swing.JTextField txtData_emprestimo;
    private javax.swing.JTextField txtId_cliente;
    private javax.swing.JTextField txtId_emprestimo;
    private javax.swing.JTextField txtId_livro;
    private javax.swing.JTextField txtSituacao_emprestimo;
    // End of variables declaration//GEN-END:variables

    private void Emprestimo() {

        String dataEmprestimo;
        int cliente_id, livro_id;

        cliente_id = Integer.parseInt(txtId_cliente.getText());
        livro_id = Integer.parseInt(txtId_livro.getText());
        dataEmprestimo = txtData_emprestimo.getText();

        EmprestimoDevolucaoDTO objEmprestimoDevolucaoDTO = new EmprestimoDevolucaoDTO();

        objEmprestimoDevolucaoDTO.setCliente_id(cliente_id);
        objEmprestimoDevolucaoDTO.setLivro_id(livro_id);
        objEmprestimoDevolucaoDTO.setDataEmprestimo(dataEmprestimo);

        EmprestimoDevolucaoDAO objEmprestimoDevolucaoDAO = new EmprestimoDevolucaoDAO();

        objEmprestimoDevolucaoDAO.Emprestimo(objEmprestimoDevolucaoDTO);

    }

    private void Devolucao() {

        int id_emprestimo, id_livro;

        id_emprestimo = Integer.parseInt(txtId_emprestimo.getText());
        id_livro = Integer.parseInt(txtId_livro.getText());

        EmprestimoDevolucaoDTO objEmprestimoDevolucaoDTO = new EmprestimoDevolucaoDTO();

        objEmprestimoDevolucaoDTO.setId_emprestimo(id_emprestimo);
        objEmprestimoDevolucaoDTO.setLivro_id(id_livro);

        EmprestimoDevolucaoDAO objEmprestimoDevolucaoDAO = new EmprestimoDevolucaoDAO();

        objEmprestimoDevolucaoDAO.Devolucao(objEmprestimoDevolucaoDTO);

    }

    private void listarValoresEmprestimoDevolucao() {

        try {

            EmprestimoDevolucaoDAO objEmprestimoDevolucaoDAO = new EmprestimoDevolucaoDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaEmprestimo.getModel();

            model.setNumRows(0);

            ArrayList<EmprestimoDevolucaoDTO> lista = objEmprestimoDevolucaoDAO.pesquisarEmprestimoDevolucao();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_emprestimo(),
                    lista.get(num).getCliente_id(),
                    lista.get(num).getLivro_id(),
                    lista.get(num).getDataEmprestimo(),
                    lista.get(num).getSituacaoEmprestimo()
                });

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + e);
        }

    }

    private void CarregarCampos() {

        int setar = tabelaEmprestimo.getSelectedRow();

        txtId_emprestimo.setText(tabelaEmprestimo.getModel().getValueAt(setar, 0).toString());
        txtId_cliente.setText(tabelaEmprestimo.getModel().getValueAt(setar, 1).toString());
        txtId_livro.setText(tabelaEmprestimo.getModel().getValueAt(setar, 2).toString());
        txtData_emprestimo.setText(tabelaEmprestimo.getModel().getValueAt(setar, 3).toString());
        txtSituacao_emprestimo.setText(tabelaEmprestimo.getModel().getValueAt(setar, 4).toString());

    }

    private void limparCampos() {

        txtId_emprestimo.setText("");
        txtId_cliente.setText("");
        txtId_livro.setText("");
        txtData_emprestimo.setText("");
        txtSituacao_emprestimo.setText("");

        txtId_cliente.requestFocus();
    }

    private void Voltar() {

        frmMenuPrincipalVIEW objfrmMenuPrincipalVIEW = new frmMenuPrincipalVIEW();

        objfrmMenuPrincipalVIEW.setVisible(true);

        dispose();

    }

}
