/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.FuncionarioDAO;
import DTO.FuncionarioDTO;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author artur
 */
public class frmFuncionarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFuncionarioVIEW
     */
    public frmFuncionarioVIEW() {
        initComponents();
        listarValoresFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNome_Funcionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf_Funcionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail_Funcionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone_Funcionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCadastrar_Funcionario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSenha_funcionario = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtId_funcionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtCargo = new javax.swing.JTextField();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionário");

        jLabel1.setText("Nome Completo");

        jLabel2.setText("CPF (Apenas números)");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        jLabel5.setText("Cargo");

        btnCadastrar_Funcionario.setText("Cadastrar");
        btnCadastrar_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_FuncionarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Senha");

        txtSenha_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha_funcionarioActionPerformed(evt);
            }
        });

        jLabel9.setText("ID");

        txtId_funcionario.setEnabled(false);

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail", "Telefone", "Cargo", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionario);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCarregarCampos.setText("Carregar Campos");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha_funcionario)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpf_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome_Funcionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimparCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(btnCadastrar_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtId_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar_Funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrar_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar_FuncionarioActionPerformed
        if (txtNome_Funcionario.getText().isEmpty() || txtCpf_Funcionario.getText().isEmpty() || txtEmail_Funcionario.getText().isEmpty() || txtTelefone_Funcionario.getText().isEmpty() || txtCargo.getText().isEmpty() || txtSenha_funcionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        } else {
            cadastrarFuncionario();
            listarValoresFuncionario();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso.");
        }
    }//GEN-LAST:event_btnCadastrar_FuncionarioActionPerformed

    private void txtSenha_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha_funcionarioActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        if (tabelaFuncionario.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário.");
        } else {
            CarregarCampos();
        }
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtId_funcionario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione e carregue um funcionário.");
        } else {
            alterarFuncionario();
            listarValoresFuncionario();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Funcionário alterado com sucesso.");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtId_funcionario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione e carregue um funcionário.");
        } else {
            excluirFuncionario();
            listarValoresFuncionario();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        limparCampos();
        Voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFuncionarioVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar_Funcionario;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCpf_Funcionario;
    private javax.swing.JTextField txtEmail_Funcionario;
    private javax.swing.JTextField txtId_funcionario;
    private javax.swing.JTextField txtNome_Funcionario;
    private javax.swing.JPasswordField txtSenha_funcionario;
    private javax.swing.JTextField txtTelefone_Funcionario;
    // End of variables declaration//GEN-END:variables

    private void cadastrarFuncionario() {

        String nome, cpf, email, telefone, cargo, senha;

        nome = txtNome_Funcionario.getText();
        cpf = txtCpf_Funcionario.getText();
        email = txtEmail_Funcionario.getText();
        telefone = txtTelefone_Funcionario.getText();
        cargo = txtCargo.getText();
        senha = new String(txtSenha_funcionario.getPassword()).trim();

        FuncionarioDTO objFuncionarioDto = new FuncionarioDTO();

        objFuncionarioDto.setNome_funcionario(nome);
        objFuncionarioDto.setCpf_funcionario(cpf);
        objFuncionarioDto.setEmail_funcionario(email);
        objFuncionarioDto.setTelefone_funcionario(telefone);
        objFuncionarioDto.setCargo(cargo);
        objFuncionarioDto.setSenha_funcionario(senha);

        FuncionarioDAO objFuncionarioDao = new FuncionarioDAO();

        objFuncionarioDao.cadastrarFuncionario(objFuncionarioDto);

    }

    private void CarregarCampos() {

        int setar = tabelaFuncionario.getSelectedRow();

        txtId_funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 0).toString());
        txtNome_Funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 1).toString());
        txtCpf_Funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 2).toString());
        txtEmail_Funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 3).toString());
        txtTelefone_Funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 4).toString());
        txtCargo.setText(tabelaFuncionario.getModel().getValueAt(setar, 5).toString());
        txtSenha_funcionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 6).toString());

    }

    private void limparCampos() {

        txtId_funcionario.setText("");
        txtNome_Funcionario.setText("");
        txtCpf_Funcionario.setText("");
        txtEmail_Funcionario.setText("");
        txtTelefone_Funcionario.setText("");
        txtCargo.setText("");
        txtSenha_funcionario.setText("");

        txtNome_Funcionario.requestFocus();
    }

    private void listarValoresFuncionario() {

        try {

            FuncionarioDAO objClienteDAO = new FuncionarioDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFuncionario.getModel();

            model.setNumRows(0);

            ArrayList<FuncionarioDTO> lista = objClienteDAO.pesquisarFuncionario();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_funcionario(),
                    lista.get(num).getNome_funcionario(),
                    lista.get(num).getCpf_funcionario(),
                    lista.get(num).getEmail_funcionario(),
                    lista.get(num).getTelefone_funcionario(),
                    lista.get(num).getCargo(),
                    lista.get(num).getSenha_funcionario()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + e);
        }

    }

    private void alterarFuncionario() {
        int id;
        String nome, cpf, email, telefone, cargo, senha;

        id = Integer.parseInt(txtId_funcionario.getText());
        nome = txtNome_Funcionario.getText();
        cpf = txtCpf_Funcionario.getText();
        email = txtEmail_Funcionario.getText();
        telefone = txtTelefone_Funcionario.getText();
        cargo = txtCargo.getText();
        senha = new String(txtSenha_funcionario.getPassword()).trim();

        FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();

        objFuncionarioDTO.setId_funcionario(id);
        objFuncionarioDTO.setNome_funcionario(nome);
        objFuncionarioDTO.setCpf_funcionario(cpf);
        objFuncionarioDTO.setEmail_funcionario(email);
        objFuncionarioDTO.setTelefone_funcionario(telefone);
        objFuncionarioDTO.setCargo(cargo);
        objFuncionarioDTO.setSenha_funcionario(senha);

        FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();

        objFuncionarioDAO.alterarFuncionario(objFuncionarioDTO);
    }

    private void excluirFuncionario() {

        int id;

        id = Integer.parseInt(txtId_funcionario.getText());

        FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();

        objFuncionarioDTO.setId_funcionario(id);

        FuncionarioDAO objClienteDAO = new FuncionarioDAO();

        objClienteDAO.excluirFuncionario(objFuncionarioDTO);
    }

    private void Voltar(){
    
        frmMenuPrincipalVIEW objfrmMenuPrincipalVIEW = new frmMenuPrincipalVIEW();

        objfrmMenuPrincipalVIEW.setVisible(true);

        dispose();
    
    }
    
}
