/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ClienteDAO;
import DTO.ClienteDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artur
 */
public class frmClienteVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmClienteVIEW
     */
    public frmClienteVIEW() {
        initComponents();
        listarValoresCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNome_Cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail_Cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone_Cliente = new javax.swing.JTextField();
        btnCadastrar_Cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jLabel10.setText("ID");

        txtId_cliente.setEnabled(false);

        jLabel1.setText("Nome Completo");

        txtNome_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_ClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF  (Coloque pontos e hífen)");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        btnCadastrar_Cliente.setText("Cadastrar");
        btnCadastrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_ClienteActionPerformed(evt);
            }
        });

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail", "Telefone"
            }
        ));
        jScrollPane2.setViewportView(tabelaCliente);

        btnCarregarCampos.setText("Carregar Campos");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail_Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpf_Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome_Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone_Cliente)
                            .addComponent(txtId_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrar_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(txtNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtCpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar_Cliente)
                        .addGap(28, 28, 28)
                        .addComponent(btnAlterar)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir)
                        .addGap(27, 27, 27)
                        .addComponent(btnVoltar)))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar_ClienteActionPerformed

        if (txtNome_Cliente.getText().isEmpty() || txtCpf_Cliente.getText().isEmpty() || txtEmail_Cliente.getText().isEmpty() || txtTelefone_Cliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        } else {
            cadastrarCliente();
            listarValoresCliente();
            limparCampos();
            
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso.");
        }

    }//GEN-LAST:event_btnCadastrar_ClienteActionPerformed

    private void txtNome_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_ClienteActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        if (tabelaCliente.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente.");
        } else {
            CarregarCampos();
        }
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (txtId_cliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione e carregue um cliente.");
        } else {
            alterarCliente();
            listarValoresCliente();
            limparCampos();
            
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso.");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtId_cliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione e carregue um cliente.");
        } else {
            excluirCliente();
            listarValoresCliente();
            limparCampos();
            
            JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso.");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        limparCampos();
        Voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClienteVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar_Cliente;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtCpf_Cliente;
    private javax.swing.JTextField txtEmail_Cliente;
    private javax.swing.JTextField txtId_cliente;
    private javax.swing.JTextField txtNome_Cliente;
    private javax.swing.JTextField txtTelefone_Cliente;
    // End of variables declaration//GEN-END:variables

    private void cadastrarCliente() {
        String nome, cpf, email, telefone;

        nome = txtNome_Cliente.getText();
        cpf = txtCpf_Cliente.getText();
        email = txtEmail_Cliente.getText();
        telefone = txtTelefone_Cliente.getText();

        ClienteDTO objClienteDto = new ClienteDTO();

        objClienteDto.setNome_cliente(nome);
        objClienteDto.setCpf_cliente(cpf);
        objClienteDto.setEmail_cliente(email);
        objClienteDto.setTelefone_cliente(telefone);

        ClienteDAO objClienteDao = new ClienteDAO();

        objClienteDao.cadastrarCliente(objClienteDto);
    }

    private void listarValoresCliente() {

        try {

            ClienteDAO objClienteDAO = new ClienteDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaCliente.getModel();

            model.setNumRows(0);

            ArrayList<ClienteDTO> lista = objClienteDAO.pesquisarCliente();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_cliente(),
                    lista.get(num).getNome_cliente(),
                    lista.get(num).getCpf_cliente(),
                    lista.get(num).getEmail_cliente(),
                    lista.get(num).getTelefone_cliente()
                });

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + e);
        }

    }

    private void CarregarCampos() {

        int setar = tabelaCliente.getSelectedRow();

        txtId_cliente.setText(tabelaCliente.getModel().getValueAt(setar, 0).toString());
        txtNome_Cliente.setText(tabelaCliente.getModel().getValueAt(setar, 1).toString());
        txtCpf_Cliente.setText(tabelaCliente.getModel().getValueAt(setar, 2).toString());
        txtEmail_Cliente.setText(tabelaCliente.getModel().getValueAt(setar, 3).toString());
        txtTelefone_Cliente.setText(tabelaCliente.getModel().getValueAt(setar, 4).toString());

    }

    private void limparCampos() {

        txtId_cliente.setText("");
        txtNome_Cliente.setText("");
        txtCpf_Cliente.setText("");
        txtEmail_Cliente.setText("");
        txtTelefone_Cliente.setText("");

        txtNome_Cliente.requestFocus();
    }

    private void alterarCliente() {
        int id;
        String nome, cpf, email, telefone;

        id = Integer.parseInt(txtId_cliente.getText());
        nome = txtNome_Cliente.getText();
        cpf = txtCpf_Cliente.getText();
        email = txtEmail_Cliente.getText();
        telefone = txtTelefone_Cliente.getText();

        ClienteDTO objClienteDTO = new ClienteDTO();

        objClienteDTO.setId_cliente(id);
        objClienteDTO.setNome_cliente(nome);
        objClienteDTO.setCpf_cliente(cpf);
        objClienteDTO.setEmail_cliente(email);
        objClienteDTO.setTelefone_cliente(telefone);

        ClienteDAO objClienteDAO = new ClienteDAO();

        objClienteDAO.alterarCliente(objClienteDTO);
    }

    private void excluirCliente() {

        int id;

        id = Integer.parseInt(txtId_cliente.getText());

        ClienteDTO objClienteDTO = new ClienteDTO();

        objClienteDTO.setId_cliente(id);

        ClienteDAO objClienteDAO = new ClienteDAO();

        objClienteDAO.excluirCliente(objClienteDTO);
    }

    private void Voltar(){
    
        frmMenuPrincipalVIEW objfrmMenuPrincipalVIEW = new frmMenuPrincipalVIEW();

        objfrmMenuPrincipalVIEW.setVisible(true);

        dispose();
    
    }
    
}
